# Generated by Django 3.2.7 on 2021-11-02 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_sighting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('where', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='sighting',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='bird',
            name='location',
            field=models.ManyToManyField(to='main_app.Location'),
        ),
    ]
