# Generated by Django 3.2.7 on 2021-11-03 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20211102_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bird',
            old_name='location',
            new_name='locations',
        ),
    ]
